export default [
  {
    ignores: ['node_modules/**', 'dist/**', '*.test.js'],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2018,
      sourceType: 'script',
    },
    env: {
      node: true,
      es6: true,
      'jest/globals': true,
    },
    plugins: ['sonarjs', 'jest'],
    extends: ['plugin:sonarjs/recommended'],
    rules: {
      strict: 'off',
      'no-underscore-dangle': 'off',
      'no-mixed-requires': 'off',
      'no-process-exit': 'off',
      'no-warning-comments': 'off',
      curly: 'off',
      'no-multi-spaces': 'off',
      'no-alert': 'off',
      'consistent-return': 'off',
      'consistent-this': ['off', 'self'],
      'func-style': 'off',
      'max-nested-callbacks': 'off',
      camelcase: 'off',

      'no-debugger': 'warn',
      'no-empty': 'warn',
      'no-invalid-regexp': 'warn',
      'no-unused-expressions': 'warn',
      'no-native-reassign': 'warn',
      'no-fallthrough': 'warn',
      'sonarjs/cognitive-complexity': 'warn',

      eqeqeq: 'error',
      'no-undef': 'error',
      'no-dupe-keys': 'error',
      'no-empty-character-class': 'error',
      'no-self-compare': 'error',
      'valid-typeof': 'error',
      'no-unused-vars': ['error', { args: 'none' }],
      'handle-callback-err': 'error',
      'no-shadow-restricted-names': 'error',
      'no-new-require': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'block-scoped-var': 'error',
      'no-else-return': 'error',
      'no-throw-literal': 'error',
      'no-void': 'error',
      radix: 'error',
      'wrap-iife': ['error', 'outside'],
      'no-shadow': 'off',
      'no-use-before-define': ['error', { functions: false }],
      'no-path-concat': 'error',
      'valid-jsdoc': ['off', { requireReturn: false, requireParamDescription: false, requireReturnDescription: false }],

      'no-spaced-func': 'error',
      'semi-spacing': 'error',
      quotes: ['error', 'single'],
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      indent: ['error', 2],
      'no-lonely-if': 'error',
      'no-floating-decimal': 'error',
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      'comma-style': ['error', 'last'],
      'no-multiple-empty-lines': ['error', { max: 1 }],
      'no-nested-ternary': 'error',
      'operator-assignment': ['error', 'always'],
      'padded-blocks': ['error', 'never'],
      'quote-props': ['error', 'as-needed'],
      'keyword-spacing': ['error', { before: true, after: true, overrides: {} }],
      'space-before-blocks': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'computed-property-spacing': ['error', 'never'],
      'space-in-parens': ['error', 'never'],
      'space-unary-ops': ['error', { words: true, nonwords: false }],
      'wrap-regex': 'error',
      'linebreak-style': ['error', 'unix'],
      semi: ['error', 'always'],
      'arrow-spacing': ['error', { before: true, after: true }],
      'no-class-assign': 'error',
      'no-const-assign': 'error',
      'no-dupe-class-members': 'error',
      'no-this-before-super': 'error',
      'no-var': 'error',
      'object-shorthand': ['error', 'always'],
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
    },
  },
];
